name: assignment8
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=2.1.1
  - python=3.11.9
  - ipython=8.25.0
  - nbconvert=7.10.0
  - pandas=2.2.2
  - scipy=1.14.1
  - py-opencv
  - matplotlib=3.9.2
  - scikit-image=0.24.0
